services:
  mysql:
    image: mysql:latest
    container_name: goodpawies-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: goodpawiesdb
      MYSQL_USER: goodpawiesuser
      MYSQL_PASSWORD: goodpawiespass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: