services:
  mariadb:
    image: mariadb:latest
    container_name: goodpawies-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: goodpawiesdb
      MARIADB_USER: goodpawiesuser
      MARIADB_PASSWORD: goodpawiespass
      TZ: Etc/UTC
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./database:/database

volumes:
  mariadb-data: