services:
  mariadb:
    image: mariadb:latest
    container_name: goodpawies-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: goodpawiesdb
      MARIADB_USER: goodpawiesuser
      MARIADB_PASSWORD: goodpawiespass
      TZ: Etc/UTC
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./database:/database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: goodpawies-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mariadb

volumes:
  mariadb-data: